[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua", args = ["--search-parent-directories", "-"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
