[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }
