---

# -------------------------------------------------
# docker-compose.yml
# -------------------------------------------------

---
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    # volumes:
    #   - .:/code
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    # depends_on:
    #   - db
    ports:
      - 8080:8080
