
diff:
	vim -d `fish -c 'echo $$__fish_data_dir'`/functions/ll.fish interactive/ll.fish
	vim -d /usr/local/Cellar/fzf/*/shell/key-bindings.fish functions/fzf_key_bindings.fish
	vim -d _fish_variables fish_variables

